
#map_file: datasets/simple-3x3/simple-3x3.map
#map_file: datasets/simple-2x5/simple-2x5.map
#map_file: datasets/empty-8x8/empty-8-8.map
#map_file: datasets/maze_32x32/maze-32-32-4.map

#generated_scenario_file: datasets/simple-3x3/generated-scen/simple.scen
#generated_scenario_file: datasets/simple-2x5/generated-scen/simple.scen
#generated_scenario_file: datasets/empty-8x8/generated-scen/empty-8-8-even-1.scen
#generated_scenario_file: datasets/maze_32x32/generated-scen/maze-32-32-4-even-1.scen

#scenario_file: dataset/3x3_2.yaml
#scenario_file: dataset/2x5_2.yaml
scenario_file: dataset/exp1_efficiency/maze-32-32-4/2_12_0.yaml

ea_params:
  crossover_rate: 0.6
  mutation_rate: 0.4
  num_generations: 50
  population_size: 50