
map_file: datasets/empty-8x8/empty-8-8.map
#map_file: datasets/maze_32x32/maze-32-32-4.map

generated_scenario_file: datasets/empty-8x8/generated-scen/empty-8-8-even-1.scen
#generated_scenario_file: datasets/maze_32x32/generated-scen/maze-32-32-4-even-1.scen

scenario_file: datasets/empty-8x8/scen-even/empty-8-8-even-1.scen

min_goals: 2
max_goals: 4
